# Use the official Node.js image.
FROM

# Create and change to the app directory.
WORKDIR

# Copy application dependency manifests to the container image.
COPY

# Install dependencies.
RUN

# Copy local code to the container image.
COPY

# Document that the service listens on port 3000.
EXPOSE

# Run the web service on container startup.
CMD 